name: Demo Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  show-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hallo World
        run: echo "Hallo World"

      - name: Multiple commands over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al
