name: Demo Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run demo commands
        run: |
          echo "Hello, World!"
          echo "This is a demo workflow."
          date
          uname -a
